server:
  port: 8090
  servlet:
    context-path: /boot
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
async:
  executor:
    thread:
      core_pool_size: 5
      max_pool_size: 10
      queue_capacity: 10
      name:
        prefix: my-thread-
spring:
  mail:
    host: smtp.qq.com
    port: 587
    username: 870137521@qq.com
    password: tcegjmsgsymjbfae
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: false
    from: 870137521@qq.com
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot-demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  task:
    scheduling:
      pool:
        size: 10
mybatis:
  type-aliases-package: com.feng.entity
  mapper-locations: mapper/*Mapper.xml
logging:
  level:
    com.feng: info
    com.feng.dao: debug
  file:
    path: D:\boot-demo-temp\logs\boot-demo.log
temp:
  file:
    upload-path: D:\boot-demo-temp
